FROM node:22-alpine AS builder

WORKDIR /app
COPY src/package*.json ./
RUN npm ci
COPY src/ .
RUN npm run build

FROM node:22-alpine

WORKDIR /app
COPY --from=builder /app/.output ./output

EXPOSE 3000
CMD ["node", "./output/server/index.mjs"]
